export const ADMIN_AUTH_LOGIN_SUCCESS = "ADMIN_AUTH_LOGIN_SUCCESS";

export const ADMIN_AUTH_LOGOUT_SUCCESS = "ADMIN_AUTH_LOGOUT_SUCCESS";
export const ADMIN_GET_PRODUCT_SUCCESS = "ADMIN_GET_PRODUCT_SUCCESS";
export const ADMIN_GET_PRODUCT_FAILURE = "ADMIN_GET_PRODUCT_FAILURE";
export const ADMIN_GET_PRODUCT_LOADING = "ADMIN_GET_PRODUCT_LOADING";

export const PAGE_UPDATE = "PAGE_UPDATE";

// export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
// export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
// export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
// export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
// export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
// export const DELETE_PRODUCT = "DELETE_PRODUCT";
