export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL="GET_PRODUCTS_FAIL"
export const UPDATE_PRODUCT_SUCCESS="UPDATE_PRODUCT_SUCCESS"
